### ISSUE TITLE
Blank Memory in OS X 10.11.3

### ISSUE THREAD

**Issue by adellhk** [zorgiepoo/Bit-Slicer#32]
It seems like Bit Slicer (1123) may be being denied access to view Chrome's memory in my OS X El Capitan (10.11.3). When I search--even 1s or 0s--my results are empty. Memory viewer for Chrome processes is empty too. I am able to access the memory for FindPointerTest.

My console gives this message repeatedly:
`2/16/16 2:52:25.000 PM kernel[0]: Sandbox: Bit Slicer(9036) System Policy: deny(1) mach-priv-task-port 9063`

A quick google suggests that there may be something wrong with the [kext signing](https://discussions.apple.com/thread/7314418?start=0&tstart=0)?

**Comment by zorgiepoo** [comment]
Sorry, looks like Chrome (starting from version 48) opted into [System Integrity Protection](https://en.wikipedia.org/wiki/System_Integrity_Protection), which I didn't until now know was possible for applications that weren't Apple's.

Here are the possible solutions I can think of starting from easiest & most recommended. I won't go in depth on them.

1. Use another web browser like Firefox (Safari won't work for the same reason as Chrome)
2. Use an older version of Chrome
3. Disable System Integrity Protection from the [Recovery System](http://www.imore.com/el-capitan-system-integrity-protection-helps-keep-malware-away)
4. Re-sign the Google Chrome app recursively inside-out with your own certificate (can be self signed)
5. Somehow find an exploit on the web that bypasses SIP, or request for/install a kext to disable it.

If you decide to try disabling the protection system-wide, note you'll lose the protection it tries to offer for you.

**Comment by adellhk** [comment]
@zorgiepoo Thanks!

**Comment by zorgiepoo** [comment]
If you still want to hack games through Google Chrome (instead of say Firefox or what not), I quickly created an Automator workflow/app that you can use. What this does is creates a copy of the app you give it (Google Chrome in this case), code signs it with an ad hoc signature (basically a fake one / only for your machine), and puts that Ad-hoc copy onto your Desktop. If you use that, Bit Slicer should be able to access it.

Note because the copied app uses a different signature, Keychain or something else may ask you to allow for access for certain items again. I'm not sure what other abnormalities may occur - that's my little warning.

Here is the workflow: https://zgcoder.net/zfw/Adhoc-Sign.zip - it finishes when it has stopped showing up in the menu bar, or when it displays a notification saying it's done.
