### ISSUE TITLE
[Feature request] Allow saving variables for easily updating several memory locations

### ISSUE THREAD

**Issue by reuben** [zorgiepoo/Bit-Slicer#37]
Would be nice to have a saved variables panel like in Cheat Engine.

Search memory, find variable, save it -> variable pops up in panel and memory value is constantly updated there. Future searches don't affect the saved variables panel, only the (existing) search panel.

**Comment by zorgiepoo** [comment]
Bit Slicer intentionally uses a unified window rather than multiple panels. If you uncheck the variable being "Active", it won't be considered for future searches. I believe I had more detail [here](https://github.com/zorgiepoo/Bit-Slicer/wiki/Search-Windows#active-variables). Multiple document windows can be created as well (*File -> New* in the menu bar)

**Comment by reuben** [comment]
Yeah, the part about the active bit wasn't too clear for me, but I just found that out while using it. Should've poked around more before creating the issue, sorry about that!

**Comment by etybyte** [comment]
Along with unchecking "Active," in Bit Slicer you can drag variables and results from one search window to another. If you want behavior like that you can open or keep open a window for "saved results," and just drag the variables you want to keep there.
