### ISSUE TITLE
Question: How to create 2000 commits on game cheating alone?

### ISSUE THREAD

**Issue by sriemer** [zorgiepoo/Bit-Slicer#41]
Hi @zorgiepoo!

I'm the current maintainer of [scanmem/GameConqueror](https://github.com/scanmem/scanmem) - the memory scanner for Linux and Linux-based smartphones.

As it's said way too rarely: You've got my big respect for creating 2000 commits on game cheating alone! 🎉 🎉 🎉 👍 

How do you do that? How do you find motivation if there are no regular contributors?

I'm the third maintainer of scanmem already and finally I've got one regular contributor. Looks like we all have that curse. Homebrew FOSS is awesome but getting the right people to work together on something is really hard.

I'm open to exchange some experience/ideas.

I'm sure that I can find inspiration in Bit-Slicer as scanmem/GC is far behind in terms of features. Our whole code needs to be cleaned up first due to inconsistent style. 😢

**Comment by zorgiepoo** [comment]
Hey. Sorry for the late response, been meaning to respond but been occupied. There probably isn't a single correct answer for me staying motivated, but I can say that I didn't write Bit Slicer out of recognition. I initially wrote it because I was not completely satisfied with an older utility called The Cheat, and because I wanted to hack around a particular video game.

As I was writing the utility, I became particularly interested in performance - fixing my naive approach of allocating many objects on the heap, heavy code inlining, parallelization across regions, caching pages/regions for future reads, boyer moore for byte arrays, etc.. Not sure how scanmem compares in performance ;).

I also cared a lot about responsiveness/ease of use/design and questioned many things - the first question I asked is if I could get by with a single table for searching and altering values. The differences between an [older version](http://d2.alternativeto.net/dist/s/eacb16d4-496e-e311-9822-002590a05f5f_2_full.png?format=jpg&width=1600&height=1600&mode=min&upscale=false) and the [current](https://screenshots.macupdate.com/JPG/34765/34765_1486526893_scr.jpg) are pretty vast.

Overall I just learned a lot by writing this utility and gained a lot of knowledge I didn't initially have. I didn't work on it that consistently - the times I put in a lot of work were when I had major new features (e.g. UI redesign, debugger features, scripting) planned for a big release; the goal here being to make the unstable program actually stable and polished again.

It's pretty awesome though scanmem/GC has had multiple contributors..! I somewhat wish I had developed a library like approach first, then maybe I'd have had a command line tool by now, and some better maintainable code. Lastly while it's been fun I'm likely at the end of my development now, but I'd be happy to share experiences. Thanks for writing. 👍

**Comment by sriemer** [comment]
Thanks for your detailed response. Exactly something like that is missing for scanmem. When I took it over, it had quite bad stability, performance and security. I've fixed all the nasty stability bugs, added Python 3 support and cared for updating it in Linux distributions. That and the moving to GitHub attracted many more users. The Python 2/3 GTK 3 GUI GameConqueror has most bugs. I'm glad that I have some help there now. Personally, I don't need a GUI but most users want it and need it.

I use Coverity Scan now for checking the C parts for security issues and I'm lucky that security experts are looking at the code. scanmem processes byte by byte. This is slow but it doesn't miss anything. The hot path in the code was horrible with divisions at every byte only for progress handling. Many real function calls were used for every byte. That really hurts on smartphones. So I've used Valgrind callgrind profiling and inlined everything in the hot path. Scan time dropped to approx. 70% less than before. The tool is optimized for small memory usage with storing results in swaths but it hasn't been optimized for performance. At least it uses /proc/$pid/mem were possible and avoids slow `ptrace()`.

On Linux we also have some trouble with ASLR/PIC/PIE if you want to make found memory addresses reproducible at every game run. So I've implemented a region type detection based on ELF knowledge and gathering of the load address of an ELF file. Results also show the match offset and a game trainer with ASLR/PIC/PIE support can readd the current load address. That makes randomized static memory values static again. I have my advanced game trainer [ugtrain](https://github.com/ugtrain/ugtrain) for that. It also uses `LD_PRELOAD` with `malloc()` and `free()` hooking to support dynamic memory hacking in a way which can be adapted easily in contrast to pointer following. As it doesn't have a GUI yet, it's hard to attract users there. Most users don't understand these advanced features any ways.

**Comment by zorgiepoo** [comment]
> Thanks for your detailed response. Exactly something like that is missing for scanmem. When I took it over, it had quite bad stability, performance and security.

Yeah, in my case, what I had to go off of was previous projects which made some mistakes (like, regarding performance). But this stuff has to be learned from *somewhere* :O...

>  I've fixed all the nasty stability bugs, added Python 3 support and cared for updating it in Linux distributions. That and the moving to GitHub attracted many more users. The Python 2/3 GTK 3 GUI GameConqueror has most bugs. I'm glad that I have some help there now. Personally, I don't need a GUI but most users want it and need it.

Interesting. I embedded Python 3 myself for the scripting functionality, although it's not a big portion of the project, and none of the source code in the repo is actually written in Python. Regarding use case, most of my users (at least that I see on YouTube) just do an equals scan and alter a value, despite what else is available. Some tutorials people create don't even go into narrowing down results - just select and edit all 100 results! Which is kind of frightening ;). I find it really interesting to observe how users use software in ways developers hadn't imagined.

> I use Coverity Scan now for checking the C parts for security issues and I'm lucky that security experts are looking at the code. scanmem processes byte by byte. This is slow but it doesn't miss anything. The hot path in the code was horrible with divisions at every byte only for progress handling. Many real function calls were used for every byte. That really hurts on smartphones. So I've used Valgrind callgrind profiling and inlined everything in the hot path. Scan time dropped to approx. 70% less than before. The tool is optimized for small memory usage with storing results in swaths but it hasn't been optimized for performance. At least it uses /proc/$pid/mem where possible and avoids slow ptrace().

Yeah, static analysis is great. Being tied to the Apple toolchain, I've been using clang as a compiler and its static analyzer. I also enable clang's AddressSanitizer (I think gcc has this now..!) for debug builds, which is great because it's a lot faster than valgrind. (Valgrind support on macOS is also poor though). There is also a ThreadSanitizer, which my code miserably fails at ;(. I've also experienced similar speed-ups after profiling (actually - I realize now my code still isn't completely inlined). Deploying on mobile sounds nice..

> On Linux we also have some trouble with ASLR/PIC/PIE if you want to make found memory addresses reproducible at every game run. So I've implemented a region type detection based on ELF knowledge and gathering of the load address of an ELF file. Results also show the match offset and a game trainer with ASLR/PIC/PIE support can readd the current load address. That makes randomized static memory values static again. I have my advanced game trainer ugtrain for that

I was just hacking on old games before I knew what ASLR was. On macOS (and I think Windows too), a binary needs its minimum OS deployment target to be greater than a certain release, in order for ASLR to kick in (compatibility reasons). I've done the same thing with region type detection, except substitute ELF for Mach-O. As far as visualization, for whatever reason I decided my program just always displays absolute memory addresses, and allows "address formulas" for variables which would be more easily explained by a [screenshot](http://i.imgur.com/86ygGqk.png). I also annotate that the variable is static in the description, and what segment name the address is associated with. I can also sometimes annotate/obtain debug symbols at an address, or a certain tag -- like if this address belongs to an allocated place created by the "Malloc Tiny". This actually gets the most use out of non-technical users - unique descriptions for variables in search process helps even if seemly jargon.

> It also uses LD_PRELOAD with malloc() and free() hooking to support dynamic memory hacking in a way which can be adapted easily in contrast to pointer following. As it doesn't have a GUI yet, it's hard to attract users there. Most users don't understand these advanced features any ways.

Though I don't know the details, it sounds like an interesting approach! We've an environment variable like that as well. I was looking into writing a recursive-depth pointer scanner (i.e, search all possible pointer candidates to this address recursively n levels deep + narrowing down process), but it seemed like a huge pain and likely computationally expensive. Another approach would be to set a watchpoint and reason about how the code computed an address. Not sure if you were referring to one of these approaches as "pointer following." Or some people scan for some byte array pattern nearby, or write a script to automate obtaining a memory location by setting a breakpoint somewhere and reading a register value when hit.
