### ISSUE TITLE
[Feature Request] Variable Libraries

### ISSUE THREAD

**Issue by Fluffybombs** [zorgiepoo/Bit-Slicer#44]
I'm very new to this, and coming from a beginner perspective, it would be awesome to have a user-friendly variable library which you could store access to variables you want to manipulate.

Basically, it would be nice if you could search for a variable, and when you found the one you wanted, be able to save it to a list, and give it a name, so you could manually edit it as much as you want without having to re-search for it. This would also allow the user to compile a list of all the variables they want to change manually, so they would have access to all of them simultaneously.

Users could also create lots of libraries with different names, so they could open one, and have all the variables they need immediately accessible. Ideally, these libraries could also be saved as documents, which would contain the addresses of each variable, so BitSlicer can locate them automatically upon reopening. Obviously it wouldn't be possible to save variables with dynamic addresses, unless BitSlicer could search by some other criteria to locate them, but for consistent addresses this would be very helpful.

I'm sure there's already a way to set something similar up manually, but it's not particularly intuitive, and I know that new users would greatly appreciate a feature like this.

**Comment by zorgiepoo** [comment]
In Bit Slicer, the user can save documents and create new documents just like they can with other document based apps like TextEdit. They can add and alter variables as they wish there. Dynamic addresses are a little more complicated, but those are possible to add as well if the user can alter the address to use pointers from static addresses.

Am I missing something here? For more info: https://github.com/zorgiepoo/Bit-Slicer/wiki/Search-Windows

**Comment by Fluffybombs** [comment]
There doesn't seem to be an easy way to save variables in the list...?
Saving a document is all well and good, but there's no obvious way to save the a variable reference to the list and allow more searches. The only way to have variables permanently in the list is by adding a variable manually, but then I suppose you'd have to modify the variable to track the value you want? I can't seem to figure out how to save a variable to the list after a search, and I apologize if I'm missing something big, but there doesn't seem to be an easy way to do it.

**Comment by zorgiepoo** [comment]
I'm trying to understand what you mean.

Documents contain a "list" of variables. They can be saved (File -> Save from menubar). If you do a search, and get thousands of results back, Bit Slicer won't save it all though (not usually an issue).

Variables can be created in the table either by doing searches or by adding variables manually (Variable -> Add Variable).

Any variable address, description, or value can be modified (double click on respective column). Value modifications do not persist across relaunches of the target, neither do dynamic addresses (but it's sometimes feasible to transform a dynamic address into a [static formula](https://github.com/zorgiepoo/Bit-Slicer/wiki/Pointers)). If you freeze a variable's value, that frozen value persists however.

When you do a search, any variable that is not marked as Active will be preserved. If there are any values that are active and that match the type of search you're doing, a narrowing scan is done. Otherwise, a full scan is done when no suitable active variables are found. This is explained in the wiki page I linked in my previous post. You can also create separate documents for separate tasks as you wish.

There are also [scripts](https://github.com/zorgiepoo/Bit-Slicer/wiki/Introduction-to-Scripting) but they don't currently have the ability to add new variables automatically.
