### ISSUE TITLE
Do Bitslicer have any community server on discord?

### ISSUE THREAD

**Issue by zigmasdirigeant** [zorgiepoo/Bit-Slicer#47]
If it doesn’t... It would be really cool to make one. :)

**Comment by Arcrammer** [comment]
Sub'd. I'd like that too!

**Comment by zorgiepoo** [comment]
There is a Bit Slicer channel on Freenode over IRC as this repository read me indicates. It used to have little activity over a year ago but I have neglected it since. Feel free to join it or set up a discord <-> irc bot (I'm not interested in setting up a pure Discord room right now). I'll try to stay in it but won't guarantee full blown devotion/support..

**Comment by zorgiepoo** [comment]
I added a [discord link](https://discordapp.com/invite/9jWe8Mf) to the read me page.
