### ISSUE TITLE
1.7.4 port to OS X 10.6.8

### ISSUE THREAD

**Issue by sergey-vlasov** [zorgiepoo/Bit-Slicer#9]
Is there some dependency that require 10.8?

**Comment by zorgiepoo** [comment]
From what I can remember:

* Auto Layout doesn't exist on 10.6 (and is somewhat bad on 10.7)
* Weak references doesn't exist on 10.6 (and is somewhat limited on 10.7)
* NSPopOver is not available on 10.6
* Unsure about third party dependencies like DDMathParser
* ..And I'm likely using other APIs not available prior to 10.8

Anyway, closing because this isn't an issue for the main project. Compatibility was dropped due to ease of development, less work for legacy maintainability, and focusing more on the majority that upgraded (which I had stats to back up).
